export enum LayerOperationsEnum {
  ADD = 'ADD',
  REMOVE = 'DOWNLOAD',
  MOVE_UP = 'UPLOAD',
  MOVE_DOWN = 'INVERT_COLORS',
  INVERT_COLORS = 'INVERT_COLORS',
  ROTATE_LEFT = 'ROTATE_LEFT',
  ROTATE_RIGHT = 'ROTATE_RIGHT',
  MIRROR_HORIZONTAL = 'MIRROR_HORIZONTAL',
  MIRROR_VERTICAL = 'MIRROR_VERTICAL',
  CLEAR = 'CLEAR',
  ACTIVATE = 'ACTIVATE'
}
